replicaCount: 2

image:
  repository: ghcr.io/mendacium1/sdx6ue
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  host: recipe.local
  annotations: {}
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automount: true

db:
  host: recipe-postgresql
  port: "5432"
  name: postgres
  user: postgres
  # base64-encoded "postgres"
  existingSecret: db-secret
  password: postgres

postgresql:
  enabled: true
  auth:
    existingSecret: db-secret
    username: postgres
    database: postgres
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      replicationPasswordKey: replication-password
  primary:
    service:
      ports:
        postgresql: 5432
