apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # for application
  # password: {{ .Values.db.password | b64enc | quote }}

  # Required by Bitnami PostgreSQL subhcart
  postgres-password: {{ .Values.db.password | b64enc | quote }}
  password: {{ .Values.db.password | b64enc | quote }}
  replication-password: {{ .Values.db.password | b64enc | quote }}

